version: '3'

services:
  kms:
    image: golang:1.12
    working_dir: /kms
    volumes:
      - ./kms:/kms
      - ./local.offen.dev.pem:/kms/local.offen.dev.pem
      - ./local.offen.dev-key.pem:/kms/local.offen.dev-key.pem
      - $GOPATH/pkg/mod:/go/pkg/mod
    environment:
      - GOPATH=/go
    ports:
      - 8081:8081
    command: go run cmd/kms/main.go -key local.offen.dev-key.pem -cert local.offen.dev.pem  -port 8081

  server:
    image: golang:1.12
    working_dir: /server
    volumes:
      - ./server:/server
      - ./local.offen.dev.pem:/server/local.offen.dev.pem
      - ./local.offen.dev-key.pem:/server/local.offen.dev-key.pem
      - $GOPATH/pkg/mod:/go/pkg/mod
    environment:
      - GOPATH=/go
      - POSTGRES_CONNECTION_STRING=postgres://postgres:develop@database:5432/postgres?sslmode=disable
      - KMS_ENCRYPTION_ENDPOINT=http://kms:8081/encrypt
    ports:
      - 8080:8080
    command: go run cmd/server/main.go -origin https://local.offen.dev:9977 -conn postgres://postgres:develop@database:5432/postgres?sslmode=disable -key local.offen.dev-key.pem -cert local.offen.dev.pem -level debug
    links:
      - database
    depends_on:
      - kms

  database:
    image: postgres:11.2
    environment:
      - POSTGRES_PASSWORD=develop

  vault:
    image: timbru31/node-chrome:slim
    working_dir: /offen/vault
    volumes:
      - .:/offen
      - ./local.offen.dev.pem:/offen/vault/local.offen.dev.pem
      - ./local.offen.dev-key.pem:/offen/vault/local.offen.dev-key.pem
    command: npm start -- --port 9977
    ports:
      - 9977:9977
    environment:
      - SERVER_HOST=https://local.offen.dev:8080
      - KMS_HOST=https://local.offen.dev:8081
      - AUDITORIUM_HOST=https://local.offen.dev:9955

  script:
    image: timbru31/node-chrome:slim
    working_dir: /offen/script
    volumes:
      - .:/offen
      - ./local.offen.dev.pem:/offen/script/local.offen.dev.pem
      - ./local.offen.dev-key.pem:/offen/script/local.offen.dev-key.pem
    command: npm start -- --port 9966
    ports:
      - 9966:9966
    environment:
      - VAULT_HOST=https://local.offen.dev:9977

  auditorium:
    image: timbru31/node-chrome:slim
    working_dir: /offen/auditorium
    volumes:
      - .:/offen
      - ./local.offen.dev.pem:/offen/auditorium/local.offen.dev.pem
      - ./local.offen.dev-key.pem:/offen/auditorium/local.offen.dev-key.pem
    command: npm start -- --port 9955
    ports:
      - 9955:9955
    environment:
      - VAULT_HOST=https://local.offen.dev:9977
