version: '3'

services:
  homepage:
    ports:
      - 8000:8000
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /website/homepage
    volumes:
      - .:/website
      - homepagedeps:/root/.local
    command: make devserver
    environment:
      DEBUG: 1

volumes:
  homepagedeps:
