version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - homepage
      - server

  server:
    image: offen/offen@sha256:fe55ba1c183eb8bb4dd19143e6fe1133d6d3b9115c94cc2150620b27adef18fc
    command: serve
    volumes:
      - ./bootstrap.yml:/bootstrap.yml
      - database:/data
    environment:
      OFFEN_APP_EVENTRETENTIONPERIOD: 4464h
      OFFEN_APP_DEVELOPMENT: '1'
      OFFEN_APP_DISABLESECURECOOKIE: '1'
      OFFEN_DATABASE_CONNECTIONSTRING: /data/offen.db
      OFFEN_SERVER_PORT: 8080
      OFFEN_SECRETS_COOKIEEXCHANGE: 8jeKYbbnywoYIZznu4HffQ==
      OFFEN_SECRETS_EMAILSALT: eypctS7SVKM1Ureb61db5Q==
    depends_on:
      - server_database

  server_database:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: develop

  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /website/homepage
    volumes:
      - .:/website
      - homepagedeps:/root/.local
    command: make devserver
    environment:
      DEBUG: 1

volumes:
  homepagedeps:
  database:
