server:
  image: golang:1.12
  working_dir: /server
  volumes:
    - ./server:/server
    - ./local.offen.dev.pem:/server/local.offen.dev.pem
    - ./local.offen.dev-key.pem:/server/local.offen.dev-key.pem
    - $GOPATH/pkg/mod:/go/pkg/mod
  environment:
    - GOPATH=/go
    - POSTGRES_CONNECTION_STRING=postgres://postgres:develop@database:5432/postgres?sslmode=disable
  ports:
    - 8080:8080
  command: go run cmd/server/main.go -conn postgres://postgres:develop@database:5432/postgres?sslmode=disable -key local.offen.dev-key.pem -cert local.offen.dev.pem
  links:
    - database

database:
  image: postgres:11.2
  environment:
    - POSTGRES_PASSWORD=develop

vault:
  image: timbru31/node-chrome:slim
  working_dir: /vault
  volumes:
    - ./vault:/vault
    - ./local.offen.dev.pem:/vault/local.offen.dev.pem
    - ./local.offen.dev-key.pem:/vault/local.offen.dev-key.pem
  command: npm start -- --port 9977
  ports:
    - 9977:9977
  environment:
    - SERVER_HOST=https://local.offen.dev:8080

script:
  image: timbru31/node-chrome:slim
  working_dir: /script
  volumes:
    - ./script:/script
    - ./local.offen.dev.pem:/script/local.offen.dev.pem
    - ./local.offen.dev-key.pem:/script/local.offen.dev-key.pem
  command: npm start -- --port 9966
  ports:
    - 9966:9966
  environment:
    - VAULT_HOST=https://local.offen.dev:9977

auditorium:
  image: timbru31/node-chrome:slim
  working_dir: /auditorium
  volumes:
    - ./auditorium:/auditorium
    - ./local.offen.dev.pem:/auditorium/local.offen.dev.pem
    - ./local.offen.dev-key.pem:/auditorium/local.offen.dev-key.pem
  command: npm start -- --port 9955
  ports:
    - 9955:9955
  environment:
    - VAULT_HOST=https://local.offen.dev:9977
