version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - homepage
      - server
      - auditorium
      - vault
      - script

  server:
    build:
      context: '.'
      dockerfile: Dockerfile.golang
    working_dir: /offen/server
    volumes:
      - .:/offen
      - ./bootstrap.yml:/offen/server/bootstrap.yml
      - serverdeps:/go/pkg/mod
    environment:
      POSTGRES_CONNECTION_STRING: postgres://postgres:develop@server_database:5432/postgres?sslmode=disable
      PORT: 8080
      DEVELOPMENT: '1'
      COOKIE_EXCHANGE_SECRET: 3P+w6QetKO3Kn8h1YyRlCw==
      EVENT_RETENTION_PERIOD: 4464h
      ACCOUNT_USER_EMAIL_SALT: JuhbRA4lCdo8rt5qVdLpk3==
      SECURE_COOKIE: 'off'
    command: refresh run
    links:
      - server_database

  server_database:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: develop

  vault:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/vault
    volumes:
      - .:/offen
      - vaultdeps:/offen/vault/node_modules
    command: npm start -- --port 9977

  script:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/script
    volumes:
      - .:/offen
      - scriptdeps:/offen/script/node_modules
    command: npm start -- --port 9966

  auditorium:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/auditorium
    volumes:
      - .:/offen
      - auditoriumdeps:/offen/auditorium/node_modules
    command: npm start -- --port 9955

  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /offen/homepage
    volumes:
      - .:/offen
      - homepagedeps:/root/.local
    command: make devserver
    ports:
      - 8000:8000
    environment:
      DEBUG: 1

volumes:
  serverdeps:
  scriptdeps:
  auditoriumdeps:
  vaultdeps:
  homepagedeps:
