version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - homepage
      - server

  server:
    image: offen/offen:latest@sha256:e14297bb6c6e03e282b0ce9d38ba2b987ef2a5de16e8943aaae3c3ca75260427
    command: serve
    volumes:
      - ./bootstrap.yml:/bootstrap.yml
    environment:
      POSTGRES_CONNECTION_STRING: postgres://postgres:develop@server_database:5432/postgres?sslmode=disable
      DEVELOPMENT: '1'
      PORT: 8080
      COOKIE_EXCHANGE_SECRET: 8jeKYbbnywoYIZznu4HffQ==
      EVENT_RETENTION_PERIOD: 4464h
      ACCOUNT_USER_EMAIL_SALT: eypctS7SVKM1Ureb61db5Q==
      SECURE_COOKIE: 'off'
    depends_on:
      - server_database

  server_database:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: develop

  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /website/homepage
    volumes:
      - .:/website
      - homepagedeps:/root/.local
    command: make devserver
    environment:
      DEBUG: 1

volumes:
  homepagedeps:
