version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./styles:/code/styles
    ports:
      - 8080:80
      - 8081:81
    depends_on:
      - homepage
      - server
      - auditorium
      - vault
      - script

  server:
    build:
      context: '.'
      dockerfile: Dockerfile.golang
    working_dir: /offen/server
    volumes:
      - .:/offen
      - ./bootstrap.yml:/offen/server/bootstrap.yml
      - serverdeps:/go/pkg/mod
    environment:
      CORS_ORIGIN: http://localhost:9977
      OPTOUT_COOKIE_DOMAIN: localhost
      POSTGRES_CONNECTION_STRING: postgres://postgres:develop@server_database:5432/postgres?sslmode=disable
      KMS_ENCRYPTION_ENDPOINT: http://kms:8081/encrypt
      PORT: 8080
      JWT_PUBLIC_KEY: http://accounts:5000/api/key
      DEVELOPMENT: '1'
      COOKIE_EXCHANGE_SECRET: Wsttdo4Z3mXV5sTc
      EVENT_RETENTION_PERIOD: 4464h
      ACCOUNT_USER_EMAIL_SALT: UwBkP24HCUYqy0Eq
    command: refresh run
    links:
      - server_database

  server_database:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: develop

  vault:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/vault
    volumes:
      - .:/offen
      - vaultdeps:/offen/vault/node_modules
    command: npm start -- --port 9977
    environment:
      - SERVER_HOST=http://localhost:8080
      - KMS_HOST=http://localhost:8081
      - SCRIPT_HOST=http://localhost:9977
      - AUDITORIUM_HOST=http://localhost:8080
      - ACCOUNTS_HOST=http://localhost:5000
      - HOMEPAGE_HOST=http://localhost:8000

  script:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/script
    volumes:
      - .:/offen
      - scriptdeps:/offen/script/node_modules
    command: npm start -- --port 9966
    environment:
      - VAULT_HOST=http://localhost:8080/vault/

  auditorium:
    build:
      context: '.'
      dockerfile: Dockerfile.node
    working_dir: /offen/auditorium
    volumes:
      - .:/offen
      - auditoriumdeps:/offen/auditorium/node_modules
    command: npm start -- --port 9955
    environment:
      - VAULT_HOST=http://localhost:8080/vault/

  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /offen/homepage
    volumes:
      - .:/offen
      - homepagedeps:/root/.local
    command: make devserver
    ports:
      - 8000:8000

volumes:
  serverdeps:
  scriptdeps:
  auditoriumdeps:
  vaultdeps:
  homepagedeps:
