version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - output:/usr/share/nginx/html
    ports:
      - 8000:80
  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /website/homepage
    volumes:
      - .:/website
      - homepagedeps:/root/.local
      - output:/website/homepage/output
    command: make regenerate
    environment:
      DEBUG: 1

volumes:
  homepagedeps:
  output:
