version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - homepage

  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /website/homepage
    volumes:
      - .:/website
      - homepagedeps:/root/.local
    command: make devserver
    environment:
      DEBUG: 1

volumes:
  homepagedeps:
