version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - homepage
      - server

  server:
    image: offen/offen:latest
    command: serve
    volumes:
      - ./bootstrap.yml:/bootstrap.yml
    environment:
      POSTGRES_CONNECTION_STRING: postgres://postgres:develop@server_database:5432/postgres?sslmode=disable
      PORT: 8080
      DEVELOPMENT: '1'
      COOKIE_EXCHANGE_SECRET: 3P+w6QetKO3Kn8h1YyRlCw==
      EVENT_RETENTION_PERIOD: 4464h
      ACCOUNT_USER_EMAIL_SALT: JuhbRA4lCdo8rt5qVdLpk3==
      SECURE_COOKIE: 'off'
    depends_on:
      - server_database

  server_database:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: develop

  homepage:
    build:
      context: '.'
      dockerfile: ./Dockerfile.python
    working_dir: /website/homepage
    volumes:
      - .:/website
      - homepagedeps:/root/.local
    command: make devserver
    environment:
      DEBUG: 1

volumes:
  homepagedeps:
