server:
  image: golang:1.12
  working_dir: /server
  volumes:
    - ./server:/server
    - $GOPATH/pkg/mod:/go/pkg/mod
  environment:
    - GOPATH=/go
    - POSTGRES_CONNECTION_STRING=postgres://postgres:develop@database:5432/postgres?sslmode=disable
  ports:
    - 8080:8080
  command: go run cmd/server/main.go -conn postgres://postgres:develop@database:5432/postgres?sslmode=disable
  links:
    - database

database:
  image: postgres:11.2
  environment:
    - POSTGRES_PASSWORD=develop

vault:
  image: node:10-alpine
  working_dir: /vault
  volumes:
    - ./vault:/vault
  command: npm start
  ports:
    - 3000:3000
