server:
  image: golang:1.12
  working_dir: /server
  volumes:
    - ./server:/server
    - ./local.offen.org.pem:/server/local.offen.org.pem
    - ./local.offen.org-key.pem:/server/local.offen.org-key.pem
    - $GOPATH/pkg/mod:/go/pkg/mod
  environment:
    - GOPATH=/go
    - POSTGRES_CONNECTION_STRING=postgres://postgres:develop@database:5432/postgres?sslmode=disable
  ports:
    - 8080:8080
  command: go run cmd/server/main.go -conn postgres://postgres:develop@database:5432/postgres?sslmode=disable -key local.offen.org-key.pem -cert local.offen.org.pem
  links:
    - database

database:
  image: postgres:11.2
  environment:
    - POSTGRES_PASSWORD=develop

vault:
  image: timbru31/node-chrome:slim
  working_dir: /vault
  volumes:
    - ./vault:/vault
    - ./local.offen.org.pem:/vault/local.offen.org.pem
    - ./local.offen.org-key.pem:/vault/local.offen.org-key.pem
  command: npm start -- --port 9977
  ports:
    - 9977:9977
