version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/offen

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "server/go.mod" }}
      - run:
          name: Download modules
          command: go mod download
      - save_cache:
          paths:
            - /go/pkg/mod
          key: v1-dependencies-{{ checksum "server/go.mod" }}
      - run:
          name: Run tests
          command: make test
