version: 2

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/offen
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install deployment dependencies
          command: |
            sudo pip install -q awscli --upgrade
      - run:
          name: Build and deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export SITEURL="https://www.offen.dev"
              export BUCKET="offen-dev-production"
              export ROBOTS_FILE="robots.txt.production"
            else
              export SITEURL="https://staging.offen.dev"
              export BUCKET="offen-dev-staging"
              export ROBOTS_FILE="robots.txt.staging"
            fi
            make build
            aws s3 sync --delete ./output/. s3://$BUCKET

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - development
